### PR TITLE
Fix for Bug #6 - local-certificate/selector issue

### PR DESCRIPTION
**Pull request by kmgoudarzi**
Change selector element lookup to correct level

Signed-off-by: Kaveh M Goudarzi <kaveh@itkaa.com>

### CODE REVIEW

**Review by fryp — CHANGES_REQUESTED** [review]
The fix looks good!  Can you add a test for this fix as well?  To prevent reintroduction of this issue in the future?

Thanks!

**Comment by fryp** [comment]
Hi @kmgoudarzi. Just checking in.  Do you think you'll be able to add a test for the fix?

**Comment by kmgoudarzi** [comment]
Hi @fryp - I can take a look next week. Would be helpful if someone can point me to the right place to add the conf processing test.

**Comment by fryp** [comment]
> Hi @fryp - I can take a look next week. Would be helpful if someone can point me to the right place to add the conf processing test.

Hi @kmgoudarzi.  Great!  I suggest taking a look at tests/Coherence.Tests/Net/Ssl.  You could add a new selector class to that directory, e.g. CertificateSelector.cs, and add a config file which references it in the tests/Coherence.Tests/Net/Ssl/Configs/ directory, and add a test method to tests/Coherence.Tests/Net/Ssl/SslTests.cs to validate that the selector is picked up and used.

Thanks!

**Comment by aseovic** [comment]
This issue is resolved by commit f3643eb.

**Pull request closed without merging**
